package util;

import java.util.Random;

/**
 * The Randomizer class provides the functionality to produce a random
 * number between a specified lower bound and upper bound. If the upper bound
 * is less than the lower bound then an IllegalArgumentException is thrown. 
 * @author	Graham Mace
 * @version	1.0 - 03/06/2006
 */
public class Randomizer {
	
	/**
	 * Variable for storing the number generated by the class
	 */
	private transient int numberGenerated;
	
	/**
	 * Create a Random class for generating the numbers
	 */
	private transient Random numberGenerator;
	
	/**
	 * Constructor for the class Randomizer
	 */
	public Randomizer() {
		numberGenerated = 0;
	}
	
	/**
	 * Returns a random number between the bounds specified. If the number cannot be
	 * generated then an IllegalArgumentException is thrown.
	 * @param	lowerBound	the lower bounds for the number to be generated
	 * @param	upperBound	the upper bounds for the number to be generated
	 */
	public int randomNum(final int lowerBound, final int upperBound) {
		if(lowerBound > upperBound) {
			throw new IllegalArgumentException("upperBound must be higher than lowerBound");
		}
		
		numberGenerator = new Random();
		final long range = (long)upperBound - (long)lowerBound + 1;
		final long fraction = (long)(range * numberGenerator.nextDouble());
		numberGenerated = (int)(fraction + lowerBound);
		return numberGenerated;
	}
	
	/**
	 * Returns a random boolean value
	 * @return	the boolean value generated
	 */
	public boolean getBoolean() {
		numberGenerator = new Random();
		return numberGenerator.nextBoolean(); 
	}
	
	/**
	 * Gets the current random number generated by this Randomizer object
	 * @return	the random number currently generated
	 */
	public int getCurrentNumber() {
		return numberGenerated;
	}
}
